export interface AutoRepairShop {
    repair_shop_id: number | null;
    owner_firstname: string;
    owner_lastname: string;
    gender: string;
    shop_name: string;
    mobile_num: string;
    password: string;
    email: string | null;
    services_offered: string[];
    longitude: string;
    latitude: string;
    creation_date: Date | null;
    profile_pic: string | null;
    shop_images: string[] | null;
    number_of_ratings: number;
    average_rating: number;
    approval_status: string;
    total_score:  number;
    profile_bg: string;
    availability: string;
    is_deleted: boolean;
};

export interface UpdateRepairShopInfo {
    owner_firstname: string | null;
    owner_lastname: string | null;
    gender: string | null;
    shop_name: string | null;
    mobile_num: string | null;
    email: string | null;
    currentPassword: string | null;
    newPassword: string | null;
    services_offered: string[] | null;
    longitude: string | null;
    latitude: string | null;
    profile_pic: string | null;
    shop_images: string[] | null;
    field: string;
};